_main_project/_main_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404

from a_user.views import api_register_view, api_login_view, api_logout_view, api_account_search_view, api_logged_in_user_view
from a_spa_frontend.views import index, custom_404_view
from a_pass import views

handler404 = custom_404_view

urlpatterns = [
    path('', index, name='js_home'),
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
	path('chat/', include('a_chat.urls', namespace='chat')),
	path('tournament/', include('a_tournament.urls', namespace='tournament')),
	path('friends/', include('a_friends.urls', namespace='friends')),
    path('register_page/', index, name='register_page'),
	path('register/', api_register_view, name='register'),
	path('login/', api_login_view, name='login'),
    path('login_check/', api_logged_in_user_view, name='login_check'),
	path('logout/', api_logout_view, name='logout'),
	path('user/', include('a_user.urls', namespace='user')),
	path('search/', api_account_search_view, name='search'),
    path('game/', include('a_game.urls'), name='game'),
    path('password/', include('a_pass.urls'), name='password'),

	# Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),

    re_path(r'^.*/', include('a_spa_frontend.urls'), name='catch_all'),

]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

_main_project/a_chat/urls.py
from django.urls import path
from . import views 


app_name = 'a_chat'

urlpatterns = [
	# path('', chat_view, name='chat'),
	path('chat/<username>', views.api_get_or_create_chatroom, name='start-chat'),
	# path('chat/room/<room_name>', chat_view, name='chat-room'),
	# path('chat/new_groupchat/', create_groupchat, name='new-groupchat'),
	# path('chat/edit/<room_name>', chatroom_edit_view, name='edit-chatroom'),
	# path('chat/delete/<room_name>', chatroom_delete_view, name='delete-chatroom'),
	# path('chat/leave/<room_name>', chatroom_leave_view, name='leave-chatroom'),
	path('chat/get_chatrooms/', views.api_get_user_chatrooms, name='get-chatrooms'),
	path('chat/<room_name>/messages/', views.api_get_last_50_chat_messages, name='get-all-chat-messages'),
]

_main_project/a_friends/urls.py
from django.urls import path
from . import views

app_name = 'a_friends'

urlpatterns = [
	path('send-friend-request/<str:username>/', views.api_send_friend_request_view, name='send_friend_request'),
	path('friend-requests/<user_id>/', views.api_friend_requests_view, name='friend_requests'),
	path('cancel-friend-request/', views.api_cancel_friend_request_view, name='cancel_friend_request'),
	path('accept-friend-request/', views.api_accept_friend_request_view, name='accept_friend_request'),
	path('decline-friend-request/', views.api_decline_friend_request_view, name='decline_friend_request'),
	path('remove-friend/', views.api_remove_friend_view, name='remove_friend'),
	path('friend-list/<user_id>/', views.api_friend_list_view, name='friend_list'),
]

_main_project/a_user/urls.py
from django.urls import path
# from a_user.views import api_profile_view, api_edit_profile_view, api_block_user_view, api_unblock_user_view, api_user_game_stats_view
from a_user import views


app_name = 'a_user'

urlpatterns = [
	path('<user_id>/', views.api_profile_view, name='profile'),
	path('<user_id>/edit/', views.api_edit_profile_view, name='edit'),
	path('<user_id>/block/', views.api_block_user_view, name='block-user'),
	path('<user_id>/unblock/', views.api_unblock_user_view, name='unblock-user'),
	# path('update_online_status/', views.api_update_online_status_view, name='update-online-status'),
	# path('check_online_status/<str:username>/', views.api_get_online_status_view, name='get-online-status'),
	path('stats/<str:stats_username>/', views.api_user_game_stats_view, name='stats'),
	path('match_history/<str:username>/', views.api_get_match_history_view, name='match-history'),
]

_main_project/a_user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Q

from a_game.models import GameSession
from a_user.forms import RegistrationForm, AccountAuthenticationForm, AccountUpdateForm
from a_user.models import Account, BlockedUser, UserGameStats
from a_friends.models import FriendList, FriendRequest
from a_friends.utils import get_friend_request_or_false
from a_friends.friend_request_status import FriendRequestStatus
from a_friends.serializers import FriendRequestSerializer

from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

from .models import Account
from .serializers import AccountSerializer


@api_view(["POST"])
def api_register_view(request, *args, **kwargs):
	user = request.user
	if user.is_authenticated:
		return Response({"message": f"You are already authenticated as {user.email}."})
	form = RegistrationForm(request.data)
	if form.is_valid():
		form.save()
		email = form.cleaned_data.get('email')
		raw_password = form.cleaned_data.get('password1')
		account = authenticate(email=email, password=raw_password)
		login(request, account)
		profile_image_url = account.profile_image.url if account.profile_image else get_default_profile_image()
		account.online = True
		account.save()
		return Response({
			"message": "Registration Successful", 
			"redirect": reverse('js_home'),
			"profile_image_url": profile_image_url,
			"username": account.username,
		}, status=status.HTTP_201_CREATED)
	else:
		return Response({"message": form.getErrors()})


@api_view(["GET"])
def api_logout_view(request):

	anonUser = request.user
	user = Account.objects.get(username=anonUser.username)
	user.online = False
	user.save()

	logout(request)
	return Response({"message": "You have been logged out."})
	# return redirect('home')


@api_view(["POST"])
def api_login_view(request, *args, **kwargs):
	context = {}
	user = request.user

	if user.is_authenticated:
		return Response({"message": f"You are already authenticated as {user.email}."})
	form = AccountAuthenticationForm(request.data)
	if form.is_valid():
		email = form.cleaned_data.get('email')
		password = form.cleaned_data.get('password')
		account = authenticate(email=email, password=password)
		profile_image_url = account.profile_image.url if account.profile_image else get_default_profile_image()
		if account:
			login(request, account)
			account.online = True
			account.save()
			print("account.online is currently set to ", account.online)
			return Response({
				"message": "Login Successful", 
				"redirect": reverse('js_home'),
				"profile_image_url": profile_image_url,
				"username": account.username,
			}, status=status.HTTP_200_OK)
		else:
			return Response({"message": "Invalid login credentials."})
	else:
		return Response({"message": form.getErrors()})


@api_view(['GET'])
def api_logged_in_user_view(request):
	user = request.user
	if user.is_authenticated:
		profile_image_url = user.profile_image.url if user.profile_image else get_default_profile_image()
		return Response({
			'id': user.id,
			'username': user.username,
			'profile_image_url': profile_image_url,
		}, status=status.HTTP_200_OK)
	return Response(status=status.HTTP_204_NO_CONTENT)


# def det_redirect_if_exists(request):
# 	redirect = None
# 	if request.GET:
# 		if request.GET.get('next'):
# 			redirect = str(request.GET.get('next'))
# 	return redirect


@api_view(['GET'])
def api_profile_view(request, *args, **kwargs):
	context = {}
	user_id = kwargs.get('user_id')

	try:
		account = Account.objects.get(pk=user_id)
	except Account.DoesNotExist:
		return Response({"message": "User not found."}, status=status.HTTP_204_NO_CONTENT)

# FriendRequestSerializer(friend_request, many=True).data

	if account:
		account_data = AccountSerializer(account).data
		context['id'] = account_data['id']
		context['email'] = account_data['email']
		context['username'] = account_data['username']
		context['profile_image'] = account_data['profile_image'] if account.profile_image else None
		context['hide_email'] = account_data['hide_email']
		context['online'] = account_data['online']

		# determine the relationship status between the logged-in user and the user whose profile is being viewed
		try:
			friend_list = FriendList.objects.get(user=account)
		except FriendList.DoesNotExist:
			friend_list = FriendList(user=account)
			friend_list.save()
		friends = friend_list.friends.all()
		context['friends'] = [AccountSerializer(friend).data for friend in friends]

		is_self = True
		is_friend = False
		user = request.user
		request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
		friend_request = None
		is_blocked = False
		
		# This check says : `If you are not looking at your own profile, then..`
		if user.is_authenticated and user != account:
			is_self = False
			if friends.filter(pk=user.id):
				is_friend = True
			else:
				is_friend = False
				# case 1: the user is not a friend and request status = `THEY_SENT_YOU`
				pending_friend_request = get_friend_request_or_false(sender=account, receiver=user) 
				if pending_friend_request:
					request_sent = FriendRequestStatus.THEY_SENT_TO_YOU.value
					context['pending_friend_request_id'] = pending_friend_request.id

				# case 2: the user is not a friend and request status = `YOU_SENT_TO_THEM`	
				elif get_friend_request_or_false(sender=user, receiver=account) is not False:
					pending_friend_request = get_friend_request_or_false(sender=user, receiver=account)
					if pending_friend_request:
						request_sent = FriendRequestStatus.SENT_BY_YOU.value
						context['pending_friend_request_id'] = pending_friend_request.id

				# case 3: the user is not a friend and request status = `NO_REQUEST_SENT`
				else:
					request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
			
			is_blocked = BlockedUser.objects.filter(user=user, blocked_user=account).exists()

		# This check means : `If you are not logged in, then..`
		elif not user.is_authenticated:
			is_self = False
		
		# This check means : `If you are looking at your own profile, then..`
		else:
			try:
				friend_request = FriendRequest.objects.filter(receiver=user, is_active=True)
			except:
				friend_request = None

		context['is_self'] = is_self
		context['is_friend'] = is_friend
		context['BASE_URL'] = settings.BASE_URL
		context['request_sent'] = request_sent
		context['friend_request'] = FriendRequestSerializer(friend_request, many=True).data
		context['is_blocked'] = is_blocked

	return Response(context, status=status.HTTP_200_OK)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def api_edit_profile_view(request, *args, **kwargs):
	user_id = kwargs.get('user_id')
	try:
		account = Account.objects.get(pk=user_id)
	except Account.DoesNotExist:
		return Response("User not found.", status=status.HTTP_204_NO_CONTENT)

	if account.pk != request.user.pk:
		return Response("You cannot edit someone else's profile.", status=status.HTTP_403_FORBIDDEN)

	form = AccountUpdateForm(request.data, request.FILES, instance=request.user)
	if form.is_valid():
		print('saving form')
		print(form.cleaned_data)
		form.save()
		return Response({"message": "Profile updated successfully."}, status=status.HTTP_200_OK)
	else:
		return Response({"errors": form.errors}, status=status.HTTP_400_BAD_REQUEST)
	context = {
		'form': form.as_p(),
		'DATA_UPLOAD_MAX_MEMORY_SIZE': settings.DATA_UPLOAD_MAX_MEMORY_SIZE,
	}
	return Response(context, status=status.HTTP_200_OK)


@api_view(['GET'])
def api_account_search_view(request, *args, **kwargs):
	context = {}

	if request.method == 'GET':
		search_query = request.GET.get('q')
		if search_query and len(search_query) > 0:
			search_results = Account.objects.filter(username__icontains=search_query).distinct()
			user = request.user
			accounts = [] # ..list structure: `[(account1, True), (account2, False), ...]` true/False is for friend status

		if user.is_authenticated:
			try:
				user_friend_list = FriendList.objects.get(user=user)
				for account in search_results:
					account_data = AccountSerializer(account).data
					accounts.append((account_data, user_friend_list.is_mutual_friend(account)))
			except FriendList.DoesNotExist:
				for account in search_results:
					account_data = AccountSerializer(account).data
					accounts.append((account_data, False))
			context['accounts'] = accounts
		else:
			for account in search_results:
				account_data = AccountSerializer(account).data
				accounts.append((account_data, False)) # False for indicating that the user is not a friend
			context['accounts'] = accounts

	return Response(context, status=status.HTTP_200_OK)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def api_block_user_view(request, user_id):
	user_to_block = get_object_or_404(Account, id=user_id)
	BlockedUser.objects.get_or_create(user=request.user, blocked_user=user_to_block)
	# messages.success(request, f'You have blocked {user_to_block.username}.')
	return Response({"message": f'You have blocked {user_to_block.username}.'}, status=status.HTTP_200_OK)
	# return redirect('a_user:profile', user_id=user_id)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def api_unblock_user_view(request, user_id):
	user_to_unblock = get_object_or_404(Account, id=user_id)
	BlockedUser.objects.filter(user=request.user, blocked_user=user_to_unblock).delete()
	# messages.success(request, f'You have unblocked {user_to_unblock.username}.')
	return Response({"message": f'You have unblocked {user_to_unblock.username}.'}, status=status.HTTP_200_OK)
	# return redirect('a_user:profile', user_id=user_id)

	

_main_project/a_user/templates/a_user/edit_profile.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

<div>
	<img src="{{ form.initial.profile_image.url }}" alt="profile_image" width="128" height="128">
</div>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}

	<input type="file" name="profile_image">

	<h6>Username</h6>
	<input type="text" name="username" placeholder="Username" required value="{{ form.initial.username }}">

	<h6>Email</h6>
	<input type="email" name="email" placeholder="Email address" required autofocus value={{ form.initial.email }}> 
	<label>
		<input type="checkbox" name="hide_email"
			{% if form.initial.hide_email %}
				checked
			{% endif %}
		>
		Hide Email
	</label>

	{% for field in form %}
		<p>
			{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
			{% endfor %}
		</p>
	{% endfor %}

	{% if form.non_field_errors %}
		<div style="color: red">
			<p>{{ form.non_field_errors }}</p>
		</div>

	{% endif %}

	<button type="submit">Save</button>
	
</form>

{% endblock content %}

_main_project/a_user/templates/a_user/login.html
{% extends 'layout.html' %}

{% load static %}

{% load allauth account socialaccount %}

{% block content %}

{% comment %}
{% endcomment %}

<style>
    /* Include the CSS for the blinking caret here if not in an external stylesheet */
    @keyframes blink-caret {
      from, to { border-color: transparent }
      50% { border-color: black }
    }

    .blinking-caret::after {
      content: '';
      display: inline-block;
      width: 1px;
      height: 1em;
      border-right: 2px solid black;
      animation: blink-caret 0.75s step-end infinite;
      vertical-align: middle;
    }
  </style>

	<h1>Login</h1>

	<form method="POST">
		{% csrf_token %}

		<img src="{% static 'images/smile_32-32.png' %}" alt="LOGO" width="40" height="40"></br>

			<!-- <div class="container"> -->

				<input class="inputEmail" type="email" name="email" placeholder="Email address" required autofocus></br>
				<input type="password" name="password" placeholder="Password" required></br>
			<!-- </div> -->

				<div class="inputEmail">Alans-MBP:~ alandunning$ npm install -g foobar</div>

			{% for field in login_form %}
			{% for error in field.errors %}
			<div style="color: red;"> 
				<p> {{ error }} </p> 
			</div>
			{% endfor %}
			{% endfor %}
			
			{% if login_form.non_field_errors %}
			<div style="color: red;"> 
				<p> {{ login_form.non_field_errors }} </p>
			</div>
			{% endif %}
			
			<button type="submit">Login</button>
	</form>
	<div>
		<a href="{% url 'password_reset' %}">Reset password?</a>
	</div>

{% comment %}
	SOCIALACCOUNT_ENABLED: {{ SOCIALACCOUNT_ENABLED }} 
	{% if SOCIALACCOUNT_ENABLED %}
		{% include "socialaccount/snippets/login.html" with page_layout="entrance" %}
	{% endif %}
{% endcomment %}
	{% include "socialaccount/snippets/login.html" with page_layout="entrance" %}


{% endblock content %}

_main_project/a_user/templates/a_user/profile.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
{% comment %}
<h1>Logged in as: {{ request.user.username }}</h1>
<a href="{% url 'account_logout' %}">Logout</a>

{% if messages %}
	{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
			{{ message }}
		</li>
	{% endfor %}
{% endif %}
{% endcomment %}

<img src="{{ request.user.profile_image.url }}" alt="Profile Image" width="64" height="64">
<p>Email</p>
{%  if is_self %}
	<h5>{{ email }}</h5>
{% else %}
	{% if hide_email %}
		<h5>**********</h5>
	{% else %}
		<h5>{{ email }}</h5>
	{% endif %}
{% endif %}
<p>Username</p>
<h5>{{ username }}</h5>

<!-- If Auth user is viewing their own profile -->
{% if is_self %}
	<a href="{% url 'a_user:edit' user_id=id %}">Edit Profile</a></br>
	<a href="{% url 'password_change' %}">Change password</a></br>
{% endif %}

{% if request.user.is_authenticated %}
	<!-- THEM sent to YOU -->
	{% if request_sent == 2 %}
		<form method="POST" action="{% url 'a_friends:accept_friend_request' %}">
			{% csrf_token %}
			<input type="hidden" name="friend_request_id" value="{{ pending_friend_request_id }}">
			<input type="submit" value="Accept Friend Request">
		</form>

		<form method="POST" action="{% url 'a_friends:decline_friend_request' %}">
			{% csrf_token %}
			<input type="hidden" name="friend_request_id" value="{{ pending_friend_request_id }}">
			<input type="submit" value="Decline Friend Request">
		</form>
	{% endif %}

	<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
	{% if is_friend == False and is_self == False and is_blocked == False %}
		<!-- You sent them a request -->
		{% if request_sent == 1 %}
			<form method="POST" action="{% url 'a_friends:cancel_friend_request' %}">
				{% csrf_token %}
				<input type="hidden" name="friend_request_id" value="{{ pending_friend_request_id }}">
				<input type="submit" value="Cancel Friend Request">
			</form>
		{% endif %}

		<!-- No requests have been sent -->
		{% if request_sent == 0 %}
			<form method="POST" action="{% url 'a_friends:send_friend_request' username=username %}">
				{% csrf_token %}
				<input type="hidden" name="receiver_id" value="{{ id }}">
				<input type="submit" value="Send Friend Request">
			</form>
		{% endif %}
	{% endif %}
		
	{% if is_friend %}
		<form method="POST" action="{% url 'a_friends:remove_friend' %}">
			{% csrf_token %}
			<input type="hidden" name="friend_id" value="{{ id }}">
			<input type="submit" value="Unfriend">
		</form>
	{% endif %}
	
	{% if friend_request %}
	<!-- Friend requests -->
		<a href="{% url 'a_friends:friend_requests' user_id=id %}">
			<span> Friend Requests ({{ friend_request|length }}) </span></br>
		</a>
	{% endif %}

	<!-- Friend list link --><br>
	<a href="{% url 'a_friends:friend_list' user_id=id %}">
		<span> Friends ({{ friends|length }}) </span></br>
	</a>

{% comment %}
	{% if is_friend %}
{% endcomment %}

	{% if not is_self and not is_blocked %}
		<a class="" href="{% url 'a_chat:start-chat' username %}">Send Private Message</a></br>
	{% endif %}

{% comment %}  
Block / Unblock logic:
{% endcomment %}
	</br>
	{% if is_self == False and not is_friend %}
		{% if is_blocked %}
			<form method="POST" action="{% url 'a_user:unblock-user' user_id=id %}">
				{% csrf_token %}
				<input type="submit" value="Unblock User">
			</form>
		{% else %}
			<form method="POST" action="{% url 'a_user:block-user' user_id=id %}">
				{% csrf_token %}
				<input type="submit" value="Block User">
			</form>
		{% endif %}
	{% endif %}

{% endif %}
	
{% endblock content %}

_main_project/a_user/templates/a_user/register.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

	<h1>Registration</h1>

	<form method="POST">
		{% csrf_token %}

		<img src="{% static 'images/smile_32-32.png' %}" alt="LOGO" width="40" height="40"></br>

		<input type="email" name="email" placeholder="Email address" required autofocus></br>
		<input type="text" name="username" placeholder="Username" required></br>
		<input type="password" name="password1" placeholder="Password" required></br>
		<input type="password" name="password2" placeholder="Confirm password" required></br>

		{% for field in registration_form %}
			{% for error in field.errors %}
				<div style="color: red;"> 
					<p> {{ error }} </p> 
				</div>
			{% endfor %}
		{% endfor %}

		{% if registration_form.non_field_errors %}
			<div style="color: red;"> 
				<p> {{ registration_form.non_field_errors }} </p>
			</div>
		{% endif %}

		<button type="submit">Register</button>
	</form>

{% endblock content %}

_main_project/a_user/templates/a_user/search_results.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

<style>
	.card {
		border: 1px solid #ccc;
		border-radius: 8px;
		padding: 16px;
		margin: 16px 0;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
	}
	.card img {
		max-width: 100px;
		border-radius: 50%;
	}
	.card h4 {
		margin: 8px 0;
	}
	.card p {
		margin: 4px 0;
	}
	.card a {
		text-decoration: none;
		color: #007bff;
	}
	.card a:hover {
		text-decoration: underline;
	}
</style>

{% if accounts %}

	{% for account in accounts %}
		<div class="card">
			<a href="{% url 'a_user:profile' user_id=account.0.id %}">
				<img src="{{ account.0.profile_image.url }}" alt="profile_image">
			</a>

			<a href="{% url 'a_user:profile' user_id=account.0.id %}">
				<h4>{{ account.0.username }}</h4>
				{% if account.1 %}
					<a href="#">Send a Message (debug.. future functionality)</a>
				{% endif %}
			</a>

			{% if account.1 %} <!-- If friends -->
				<p> Friends </p>
			{% else %}
				{% if account.0 != request.user %} <!-- If not friends -->
					<p> Not Friends </p>
				{% endif %}
			{% endif %}

			{% if account.0 == request.user %} <!-- If you -->
				<p> This is you </p>
			{% endif %}
		</div>
	{% endfor %}
	
{% else %} <!-- If no friends -->
	<p> No results </p>
{% endif %}

{% endblock content %}