_main_project/_main_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404

from a_user.views import api_register_view, api_login_view, api_logout_view, api_account_search_view, api_logged_in_user_view
from a_spa_frontend.views import index, custom_404_view
from a_pass import views

handler404 = custom_404_view

urlpatterns = [
    path('', index, name='js_home'),
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
	path('chat/', include('a_chat.urls', namespace='chat')),
	path('tournament/', include('a_tournament.urls', namespace='tournament')),
	path('friends/', include('a_friends.urls', namespace='friends')),
    path('register_page/', index, name='register_page'),
	path('register/', api_register_view, name='register'),
	path('login/', api_login_view, name='login'),
    path('login_check/', api_logged_in_user_view, name='login_check'),
	path('logout/', api_logout_view, name='logout'),
	path('user/', include('a_user.urls', namespace='user')),
	path('search/', api_account_search_view, name='search'),
    path('game/', include('a_game.urls'), name='game'),
    path('password/', include('a_pass.urls'), name='password'),

	# Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),

    re_path(r'^.*/', include('a_spa_frontend.urls'), name='catch_all'),

]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

_main_project/a_chat/urls.py
from django.urls import path
from . import views 


app_name = 'a_chat'

urlpatterns = [
	# path('', chat_view, name='chat'),
	path('chat/<username>', views.api_get_or_create_chatroom, name='start-chat'),
	# path('chat/room/<room_name>', chat_view, name='chat-room'),
	# path('chat/new_groupchat/', create_groupchat, name='new-groupchat'),
	# path('chat/edit/<room_name>', chatroom_edit_view, name='edit-chatroom'),
	# path('chat/delete/<room_name>', chatroom_delete_view, name='delete-chatroom'),
	# path('chat/leave/<room_name>', chatroom_leave_view, name='leave-chatroom'),
	path('chat/get_chatrooms/', views.api_get_user_chatrooms, name='get-chatrooms'),
	path('chat/<room_name>/messages/', views.api_get_last_50_chat_messages, name='get-all-chat-messages'),
]

_main_project/a_user/urls.py
from django.urls import path
# from a_user.views import api_profile_view, api_edit_profile_view, api_block_user_view, api_unblock_user_view, api_user_game_stats_view
from a_user import views


app_name = 'a_user'

urlpatterns = [
	path('<user_id>/', views.api_profile_view, name='profile'),
	path('<user_id>/edit/', views.api_edit_profile_view, name='edit'),
	path('<user_id>/block/', views.api_block_user_view, name='block-user'),
	path('<user_id>/unblock/', views.api_unblock_user_view, name='unblock-user'),
	# path('update_online_status/', views.api_update_online_status_view, name='update-online-status'),
	# path('check_online_status/<str:username>/', views.api_get_online_status_view, name='get-online-status'),
	path('stats/<str:stats_username>/', views.api_user_game_stats_view, name='stats'),
	path('match_history/<str:username>/', views.api_get_match_history_view, name='match-history'),
]

_main_project/a_chat/models.py
from django.db import models
from a_user.models import Account
import shortuuid


# The following model / db table will be storing chatrooms.
class ChatRoom(models.Model):
	room_name = models.CharField(max_length=128, unique=True, default=shortuuid.uuid)
	groupchat_name = models.CharField(max_length=128, null=True, blank=True)
	admin = models.ForeignKey(Account, related_name='group_chats', blank=True, null=True, on_delete=models.SET_NULL)
	users_online = models.ManyToManyField(Account, related_name='online_in_rooms', blank=True)
	members = models.ManyToManyField(Account, related_name='chat_rooms', blank=True) 
	is_private = models.BooleanField(default=False)

	def __str__(self):
		return self.room_name


# The following model / db table will be storing messages.
class Message(models.Model):
	room = models.ForeignKey(ChatRoom, related_name='chat_messages', on_delete=models.CASCADE,)
	author = models.ForeignKey('a_user.Account', on_delete=models.CASCADE,)
	msg_content = models.CharField(max_length=512)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.author.username} : {self.msg_content}'
	
	class Meta:
		ordering = ['-created']

_main_project/a_chat/forms.py
from django import forms
from django.forms import ModelForm

from .models import Message, ChatRoom


class ChatMessageCreateForm(ModelForm):
	class Meta:
		model = Message
		fields = ['msg_content']
		widgets = {
			'msg_content': forms.TextInput(attrs={
    			'placeholder': 'Type your message here...', 
       			'maxlength': '512',
        		'autofocus': True,
				'style': 'width: 400px;'
        	}),
		}
		labels = {
			'msg_content': '',
		}


class NewGroupChatForm(ModelForm):
	class Meta:
		model = ChatRoom
		fields = ['groupchat_name']
		widgets = {
			'groupchat_name': forms.TextInput(attrs={
				'placeholder': 'Enter group chat name...',
				'maxlength': '128',
				'autofocus': True,
				'style': 'width: 400px;'
			}),
		}
		labels = {
			'groupchat_name': '',
		}


class ChatRoomEditForm(ModelForm):
	class Meta:
		model = ChatRoom
		fields = ['groupchat_name']
		widgets = {
			'groupchat_name': forms.TextInput(attrs={
				'placeholder': 'Enter group chat name...',
				'maxlength': '128',
			}),
		}
		labels = {
			'groupchat_name': '',
		}

_main_project/a_chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib import messages

from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from .models import ChatRoom, Message
from .forms import ChatMessageCreateForm, NewGroupChatForm, ChatRoomEditForm
from a_user.models import Account, BlockedUser


# def chat_view(request, room_name='public-chat'):
# 	chat_room = get_object_or_404(ChatRoom, room_name=room_name)
# 	chat_messages = chat_room.chat_messages.all()[:20]
# 	form = ChatMessageCreateForm()
# 	other_user = None

# 	if chat_room.is_private:
# 		if request.user not in chat_room.members.all():
# 			raise Http404()
# 		for member in chat_room.members.all():
# 			if member != request.user:
# 				other_user = member
# 				break
	
# 	if chat_room.groupchat_name:
# 		if request.user not in chat_room.members.all():
# 			chat_room.members.add(request.user)

# 	if request.htmx:
# 		form = ChatMessageCreateForm(request.POST)
# 		if form.is_valid():
# 			new_message = form.save(commit=False)
# 			new_message.room = chat_room
# 			new_message.author = request.user
# 			new_message.save()

# 			# return redirect('a_chat:chat')
# 			context = {
# 				'message': new_message,
# 				'user': request.user,
# 			}
# 			return render(request, 'a_chat/partials/chat_message_p.html', context)

# 	context = {
# 		'chat_room': chat_room,
# 		'chat_messages': chat_messages,
# 		'form': form,
# 		'other_user': other_user,
# 	}

# 	return render(request, 'a_chat/chat.html', context)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def api_get_or_create_chatroom(request, username):
	if request.user.username == username:
		return Response({'error': 'You cannot chat with yourself.'}, status=status.HTTP_400_BAD_REQUEST)

	other_user = Account.objects.get(username=username)

	# Check if the user is blocked by any of the members of the chat room.
	if BlockedUser.objects.filter(user=other_user, blocked_user=request.user).exists():
		return Response({'error': 'You are blocked by this user and cannot send messages.'}, status=status.HTTP_403_FORBIDDEN)
	
	# Check if the user has blocked any of the members of the chat room.
	if BlockedUser.objects.filter(user=request.user, blocked_user=other_user).exists():
		return Response({'error': 'You have blocked this user and cannot send messages.'}, status=status.HTTP_403_FORBIDDEN)

	my_chatrooms = request.user.chat_rooms.filter(is_private=True)

	if my_chatrooms.exists():
		private_room = None
		for room in my_chatrooms:
			if other_user in room.members.all():
				private_room = room
				break
			# else:
			# 	print("idk what to do")
			# 	room = ChatRoom.objects.create(is_private=True)
			# 	room.members.add(request.user, other_user)
		if not private_room:
			private_room = ChatRoom.objects.create(is_private=True)
			private_room.members.add(request.user, other_user)
	else:
		private_room = ChatRoom.objects.create(is_private=True)
		private_room.members.add(request.user, other_user)

	return Response({'room_name': private_room.room_name}, status=status.HTTP_200_OK);


# def create_groupchat(request):
# 	form = NewGroupChatForm()

# 	if request.method == 'POST':
# 		form = NewGroupChatForm(request.POST)
# 		if form.is_valid():
# 			new_groupchat = form.save(commit=False)
# 			new_groupchat.admin = request.user
# 			new_groupchat.save()
# 			new_groupchat.members.add(request.user)
# 			return redirect('a_chat:chat-room', new_groupchat.room_name)

# 	context = {
# 		'form': form,
# 	}
# 	return render(request, 'a_chat/create_groupchat.html', context)


# def chatroom_edit_view(request, room_name):
# 	chat_room = get_object_or_404(ChatRoom, room_name=room_name)
# 	if request.user != chat_room.admin:
# 		raise Http404()

# 	form = ChatRoomEditForm(instance=chat_room)

# 	if request.method == 'POST':
# 		form = ChatRoomEditForm(request.POST, instance=chat_room)
# 		if form.is_valid():
# 			form.save()
			
# 			remove_members = request.POST.getlist('remove_members')
# 			for member_id in remove_members:
# 				member = Account.objects.get(id=member_id)
# 				chat_room.members.remove(member)

# 			return redirect('a_chat:chat-room', room_name=room_name)

# 	context = {
# 		'form': form,
# 		'chat_room': chat_room,
# 	}
# 	return render(request, 'a_chat/chatroom_edit.html', context)


# def chatroom_delete_view(request, room_name):
# 	chat_room = get_object_or_404(ChatRoom, room_name=room_name)
# 	if request.user != chat_room.admin:
# 		raise Http404()

# 	if request.method == 'POST':
# 		chat_room.delete()
# 		messages.success(request, 'Group chat deleted successfully.')
# 		return redirect('home')

# 	context = {
# 		'chat_room': chat_room,
# 	}
# 	return render(request, 'a_chat/chatroom_delete.html', context)


# def chatroom_leave_view(request, room_name):
# 	chat_room = get_object_or_404(ChatRoom, room_name=room_name)
# 	if request.user not in chat_room.members.all():
# 		raise Http404()

# 	if request.method == 'POST':
# 		chat_room.members.remove(request.user)
# 		messages.success(request, 'You have left the group chat.')
# 		return redirect('home')

# 	context = {
# 		'chat_room': chat_room,
# 	}
# 	return render(request, 'a_chat/chatroom_leave.html', context)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def api_get_user_chatrooms(request):
	# Getting BlockedUser objects where the current user is the blocked_user.
	blocked_by_users = BlockedUser.objects.filter(blocked_user=request.user).values_list('user', flat=True)

	# chatrooms = request.user.chat_rooms.all()
	# Take out the chatrooms where the other user has blocked the current user: 
	chatrooms = request.user.chat_rooms.exclude(admin__in=blocked_by_users)
	chatrooms_data = []

	for chatroom in chatrooms:
		chatroom_data = {
			'room_name': chatroom.room_name,
			'is_private': chatroom.is_private,
			'groupchat_name': chatroom.groupchat_name,
			# 'admin': chatroom.admin.username,
			'members': [member.username for member in chatroom.members.all()],
		}
		chatrooms_data.append(chatroom_data)
	
	return Response(chatrooms_data, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def api_get_last_50_chat_messages(request, room_name):
	chat_room = get_object_or_404(ChatRoom, room_name=room_name)
	chat_messages = chat_room.chat_messages.all().order_by('-created')[:50]
	messages_data = [{'author': message.author.username, 'content': message.msg_content, 'created': message.created} for message in chat_messages]
	messages_data.reverse()
	return Response(messages_data, status=status.HTTP_200_OK)

_main_project/a_chat/templates/a_chat/chat.html
{% extends 'layout.html' %}
{% block content %}

<style>
	.chat-container {
        margin: 0 auto 8px auto;
        border-radius: 5px;
        background-color: #f8f9fa;
        border: 2px solid #ccc;
        padding: 10px;
        height: 300px;
        width: 100%;
        max-width: 500px;
        overflow-y: auto;
        box-sizing: border-box;
    }

	#chat_window {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

	.chat-input {
		padding: 10px;
		border-radius: 5px;
		border: 2px solid #ccc;
		box-sizing: border-box;
	}
</style>
{% comment %}
{% endcomment %}

<wrapper>
    <div id="chat_window">
	{% if chat_room.groupchat_name %}
		<h3>{{ chat_room.groupchat_name }}</h3>

		{% if user == chat_room.admin %}
			<a href="{% url 'a_chat:edit-chatroom' chat_room.room_name %}">
				<span class="material-symbols-outlined">edit</span>
				Edit
			</a>
		{% endif %}
	{% endif %}
        <div>
			{% if other_user %}
				<div id="online-icon" class="...this-is-updated-with-htmx-in-partials/online_count.html-to-do"></div>
				<a href="{% url 'a_user:profile' other_user.id %}">
					<div>
						<span class="">Private Chat with {{ other_user.username }}</span>
					</div>
				</a>
			
			{% elif chat_room.groupchat_name %}
				<ul id="groupchat-members">
					{% for member in chat_room.members.all %}
						<li>
							<a href="{% url 'a_user:profile' member.id %}">
								<img src="{{ member.profile_image.url }}" alt="user img" width="16" height="16">
								{{ member.username | slice:":10" }}
							</a>
						</li>
					{% endfor %}
				</ul>

			{% else %}
				<div id="online-icon" class="...this-is-updated-with-htmx-in-partials/online_count.html-to-do"></div>
				<span id="online-count"></span>online
			{% endif %}
        </div>
        <div id='chat_container' class="chat-container">
			<div id='chat_messages'>
				{% for message in chat_messages reversed %}
					{% include 'a_chat/chat_message.html' %}
				{% endfor %}
			</div>
        </div>
        <div class="">
            <div class="">
                <form id="chat_message_form" class="chat-input"
					hx-ext="ws"
					ws-connect="/ws/chatroom/{{ chat_room.room_name }}/"
					ws-send
					_="on htmx:wsAfterSend reset() me"
				>
					{% csrf_token %}
					{{ form }}
                </form>
            </div>
        </div>
    </div>

	<div>
		{% if chat_room.members.exists %}
			<a href="{% url 'a_chat:leave-chatroom' chat_room.room_name %}">Leave Chatroom</a>
		{% endif %}
	</div>

</wrapper>

{% endblock content %}

{% block scripts %}

<script>

	function scrollToBottom(time=0) {
        setTimeout(function() {
            const container = document.getElementById('chat_container');
            container.scrollTop = container.scrollHeight;
        }, time);
    }
    scrollToBottom()

</script>

{% endblock scripts %}

_main_project/a_chat/templates/a_chat/chat_message.html
{% if message.author == user %}	
	<div class="">
		<a href="{% url 'a_user:profile' user_id=message.author.id %}"><strong>me</strong></a>
		<span>: {{ message.msg_content }}</span>
	</div>
{% else %}
	<div class="">
		<a href="{% url 'a_user:profile' user_id=message.author.id %}">{{ message.author.username }}</a>
		<span>: {{ message.msg_content }}</span>
	</div>
{% endif %}

{% comment %}
{% endcomment %}

_main_project/a_chat/templates/a_chat/chatroom_delete.html
{% extends "layout.html" %}

{% block content %}

<h1>Delete this chatroom ?</h1>

<h2>"{{ chat_room.groupchat_name }}"</h2>

<form method="POST">
	{% csrf_token %}

	<button type="submit">Yes, delete</button>
	</br>
	<a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

_main_project/a_chat/templates/a_chat/chatroom_edit.html
{% extends 'layout.html' %}

{% block content %}

<h1>Edit Chatroom</h1>

<form method="POST">
	{% csrf_token %}
	{{ form }}

	<h2>Members</h2>
	{% for member in chat_room.members.all %}
		<li>
			<img src="{{ member.profile_image.url }}" alt="user img" width="16" height="16">
			{{ member.username | slice:":10" }}

			{% if member != chat_room.admin %}
				<input type="checkbox" name="remove_members" value="{{ member.id }}"/>
			{% endif %}
		</li>

	{% endfor %}

	<button type="submit">Update</button>
</form>

<a href="{% url 'a_chat:delete-chatroom' chat_room.room_name %}">Delete Chatroom</a>

{% comment %}
{% endcomment %}

{% endblock %}

_main_project/a_chat/templates/a_chat/chatroom_leave.html
{% extends "layout.html" %}

{% block content %}

<h1>Leave this chatroom ?</h1>

<h2>"{{ chat_room.groupchat_name }}"</h2>

<form method="POST">
	{% csrf_token %}

	<button type="submit">Yes, I am leaving..</button>
	</br>
	<a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

_main_project/a_chat/templates/a_chat/create_groupchat.html
{% extends 'layout.html' %}


{% block content %}

<style>
	.button {
		padding: 10px;
		border-radius: 5px;
		background-color: lightgreen;
		border: 2px solid #ccc;
		box-sizing: border-box;
	}

	.input-field {
		padding: 10px;
		border-radius: 5px;
		border: 2px solid #ccc;
		box-sizing: border-box;
	}
</style>

<h1>Create New Group Chat</h1>

<form class="input-field" method="POST">
	{% csrf_token %}
	{{ form }}

	<button class="button" type="submit">Create new chat room</button>
</form>


{% endblock %}